exp_name: bert_slider
trainer:
  auto_select_gpus: True
  auto_lr_find: True
  gpus: 1
  max_epochs: 1
model:
  transformer: roberta-base
  embedding_method: attn_pool
  num_classes: 23
  learning_rate: 5e-5
data:
  inner_batch_size: 16
  batch_size: 2
  window_size: 5
  dilation_gap: 0